-- liquibase formatted sql

-- changeset system:003-create-roles-table
CREATE TABLE roles (
    id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE INDEX idx_roles_name ON roles (name);
-- rollback DROP INDEX idx_roles_name;
-- rollback DROP TABLE roles;
