CREATE TABLE EVENT_PUBLICATION (
    ID                     UUID            NOT NULL PRIMARY KEY,
    COMPLETION_DATE        TIMESTAMP WITH TIME ZONE,
    EVENT_TYPE             VARCHAR(512)    NOT NULL,
    LISTENER_ID            VARCHAR(512)    NOT NULL,
    PUBLICATION_DATE       TIMESTAMP WITH TIME ZONE NOT NULL,
    SERIALIZED_EVENT       TEXT            NOT NULL,
    STATUS                 VARCHAR(50),
    COMPLETION_ATTEMPTS    INT             DEFAULT 0,
    LAST_RESUBMISSION_DATE TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_event_publication_by_completion_date ON EVENT_PUBLICATION (COMPLETION_DATE);
